title: Gilgamesh AI
baseurl: /
url: https://docs.gilgamesh.ai
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
include: ['_pages']
collections_dir: collections
collections:
  - examples
